"""correct column name in review table

Revision ID: 2b29db457de7
Revises: c53d35142df7
Create Date: 2024-03-24 11:23:14.644515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b29db457de7'
down_revision = 'c53d35142df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_reviews_items_id_items', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_item_id_items'), 'items', ['item_id'], ['id'])
        batch_op.drop_column('items_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_reviews_item_id_items'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_items_id_items', 'items', ['items_id'], ['id'])
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
